### PR TITLE
docs: add documentation for `<Motion>` component

### PR DESCRIPTION
**Pull request by BobbieGoede**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSDoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Adds a very basic page to document the `<Motion>` component, this is essentially a modified version of the "Directive Usage" page. I'm not exactly good at writing documentation so feel free to add more details if necessary. I left out documentation for the `:instance` prop on purpose as this doesn't seem to do anything, this is something to look into later.

@Tahul 
If this documentation is sufficient (for now), I think we should publish a new release 😄

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Tahul** [comment]
looks great ; what would you think of adding an example for that component, showcasing its features?

**Comment by BobbieGoede** [comment]
I added an example for the `<Motion>` and `<MotionGroup>` components, the functionality is mostly the same as the `v-motion` directive except the components should work better for SSR, not sure how we would showcase this 😅. 

On a separate note, maybe a future improvement to `<MotionGroup>` could be to allow passing a separate `delay` or `duration` prop that accepts a function, this would make it possible to easily create staggered animations.

For now I'm mostly curious if people will use the components over the directive, the docs will probably need further reworks to guide users in that direction.

**Comment by BobbieGoede** [comment]
I have opened a draft PR https://github.com/vueuse/motion/pull/193 that demonstrates one way we could improve the `<MotionGroup>` component.

That will be something to explore a bit later, I prefer publishing a release first before adding new features for the sake of stability 😅

**Comment by Tahul** [comment]
> For now I'm mostly curious if people will use the components over the directive, the docs will probably need further reworks to guide users in that direction.

Same, let's see :)

**Pull request merged**
