### PR TITLE
Forgo deprecated functions and typescript flags. Update types to make the tests pass again, as well as allow the demo, docs, and playground to build on dev

### PR DESCRIPTION
**Pull request by alex-eliot**
By Nuxt 3.5, it won't be possible to access properties from the top level of the runtimeConfig, esssentially breaking this library once that version releases. To prevent that, I updated the motion options to go under the "public" field of the config.

The `suppressImplicitAnyIndexErrors` flag in TypeScript is deprecated. I removed it, and tried to make the keys type-safe as much as I could instead of relying on `@ts-ignore` or `@ts-ignore-error`. I'm welcome to have it back like that for consistency because I understand how `keyof typeof x` is not the most beautiful around...

As a result of stronger typing with the removal of that flag, there are plenty of files that've changed (only in typings). I'm still not entirely sure about the parts with MotionProperties, but upon normal usage of useMotion, for example, the properties are well-typed. Still, I'd love another opinion on that.

Please tell if I have to change anything or if I did something wrong. Thank you!

### CODE REVIEW

**Comment by Idered** [comment]
Hey @Tahul can we get this merged?

**Comment by cpreston321** [comment]
Just FYI, `main` is super out of date compared to `feat/v2` which @Tahul has been working on for all the beta releases. 

I am assuming he will not merge this because of that. So I made a PR for this issue as a draft to fix the bugs based on the new branch.

**Comment by Tahul** [comment]
Hey @alex-eliot ; @Idered ; @cpreston321 ;

This is very kind of you to work on such big PRs, I really appreciate it.

I'm reviewing both right now to get this working on latest versions of Nuxt as soon as possible.

**Comment by Tahul** [comment]
Hey @alex-eliot :)

I decided to merge the @cpreston321 update branch, and then merge and release the v2 version.

Thank you so much for making initial efforts on this, this is greatly appreciated.

As you seem to have wandered quite a lot through the code of this repository, would you be interested in joining it as a maintainer?

@cpreston321 and I will be continuing efforts on this package towards a v3; and I would greatly appreciate other people joining it!

Feel free to reach me out on Discord: **Tahul#3734**

**Pull request closed without merging**
